call build-cpp-bsw.bat
call build-cpp-byt.bat
call build-cpp-hswbdw-book.bat
call build-cpp-hswbdw-box.bat
call build-cpp-ivb-book.bat
call build-cpp-link.bat
call build-cpp-skl.bat
call build-cpp-snb-book.bat
call build-cpp-snb-box.bat
call build-cpp-kbl-box.bat